title: Alex Haslehurst
email: alex.haslehurst@gmail.com
description: Alex Haslehurst's personal website.
baseurl: ""
url: https://ax-h.com
excerpt_separator: <!--more-->

theme: null

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Alex Haslehurst
      is_post: true

disqus:
  shortname: ax-h

google_analytics: UA-110996722-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .git/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - src/
  - dist
  - webpack.config.js
  - package.json
  - package-lock.json
  - build.sh
  - README.md
